export const GET_DATA = "GET_DATA_SUCCESS";
export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_FAILED = "GET_DATA_FAILED";

export const SEARCH_DATA = "SEARCH_DATA_SUCCESS";
export const SEARCH_DATA_REQUEST = "SEARCH_DATA_REQUEST";
export const SEARCH_DATA_FAILED = "SEARCH_DATA_FAILED";

export const RESET_DATA = "RESET_DATA";